nelmio_api_doc:
    documentation:
        info:
            title: API test task NDV
            description: test task for interview NDV
            version: 1.0.0
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
